using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RubberIntelligence.API.Data.Repositories;
using RubberIntelligence.API.Modules.Dpp.DTOs;
using RubberIntelligence.API.Modules.Dpp.Models;
using RubberIntelligence.API.Modules.Dpp.Services;

namespace RubberIntelligence.API.Modules.Dpp.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class DppController : ControllerBase
    {
        private readonly GeminiOcrService _ocrService;
        private readonly OnnxDppService _onnxDppService;
        private readonly DppEncryptionService _encryptionService;
        private readonly IDppRepository _dppRepository;
        private readonly IUserRepository _userRepository; // To validate user existance if needed, mostly reliance on Claims
        private readonly IWebHostEnvironment _env;

        public DppController(
            GeminiOcrService ocrService, 
            OnnxDppService onnxDppService, 
            DppEncryptionService encryptionService,
            IDppRepository dppRepository,
            IUserRepository userRepository,
            IWebHostEnvironment env)
        {
            _ocrService = ocrService;
            _onnxDppService = onnxDppService;
            _encryptionService = encryptionService;
            _dppRepository = dppRepository;
            _userRepository = userRepository;
            _env = env;
        }

        [Authorize(Roles = "Buyer,Admin")] // Only Buyers (and Admin) upload documents
        [HttpPost("upload")]
        public async Task<IActionResult> UploadDocument([FromForm] DocumentUploadRequest request)
        {
            if (request.File == null || request.File.Length == 0)
                return BadRequest("No file uploaded.");

            var userId = User.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value ?? "anonymous";

            // 1. Save temp file
            var uploadsFolder = Path.Combine(_env.ContentRootPath, "Uploads", "Dpp");
            Directory.CreateDirectory(uploadsFolder);
            var tempPath = Path.Combine(uploadsFolder, Guid.NewGuid() + Path.GetExtension(request.File.FileName));
            
            using (var stream = new FileStream(tempPath, FileMode.Create))
            {
                await request.File.CopyToAsync(stream);
            }

            // 2. Perform OCR (Gemini)
            string extractedText;
            try 
            {
                using (var fileStream = new FileStream(tempPath, FileMode.Open, FileAccess.Read))
                {
                    extractedText = await _ocrService.ExtractTextAsync(fileStream, request.File.ContentType);
                }
            }
            catch (HttpRequestException ex)
            {
                if (ex.StatusCode == System.Net.HttpStatusCode.TooManyRequests)
                {
                     return StatusCode(429, new { error = "Gemini API Quota Exceeded. Please try again later.", details = ex.Message });
                }
                
                return StatusCode((int)(ex.StatusCode ?? System.Net.HttpStatusCode.InternalServerError), new { error = "OCR Service Failed", details = ex.Message });
            }
            catch (Exception ex)
            {
                 return StatusCode(500, new { error = "Internal Server Error during processing", details = ex.Message });
            }

            if (string.IsNullOrWhiteSpace(extractedText))
            {
                extractedText = "No readable text found.";
            }

            // 3. Classify
            var classificationResult = _onnxDppService.ClassifyDocument(extractedText, request.File.FileName);

            string finalStoredPath = tempPath;
            bool isEncrypted = false;

            // 4. Encrypt if necessary
            if (classificationResult.IsEncrypted)
            {
                var encryptedPath = tempPath + ".enc";
                await _encryptionService.EncryptFileAsync(request.File, encryptedPath);
                
                // Delete original plain file if sensitive
                if (System.IO.File.Exists(tempPath)) System.IO.File.Delete(tempPath);
                
                finalStoredPath = encryptedPath;
                isEncrypted = true;
            }

            // 5. Save Record to DB
            var dppDoc = new DppDocument
            {
                // Id is auto-generated by MongoDB usually, but if DppDocument defines it as string/ObjectId, handle appropriately.
                // Assuming it's auto-gen or we can set it.
                OriginalFileName = request.File.FileName,
                StoredFilePath = finalStoredPath,
                ContentType = request.File.ContentType,
                Classification = classificationResult.Classification,
                ConfidenceScore = classificationResult.ConfidenceScore,
                IsEncrypted = isEncrypted,
                UploadedAt = DateTime.UtcNow,
                UploadedBy = userId,
                ExtractedTextSummary = classificationResult.ExtractedText, // Only snippet stored
                DetectedKeywords = classificationResult.InfluentialKeywords
            };

            await _dppRepository.CreateAsync(dppDoc);

            // Update result with ID for Frontend
            // DppResult (DTO) usually doesn't have ID, might need to wrap or extend.
            // For now, return the entity or an anonymous object.
            
            return Ok(new { 
                dppId = dppDoc.Id, // Ensure Model generates this
                result = classificationResult
            });
        }

        [Authorize(Roles = "Exporter,Admin")]
        [HttpGet("{id}/access")]
        public async Task<IActionResult> GetDocumentAccess(string id)
        {
            var doc = await _dppRepository.GetByIdAsync(id);
            if (doc == null) return NotFound("Document not found");

            // Exporters can view content.
            // If encrypted, decrypt on the fly.
            
            if (!System.IO.File.Exists(doc.StoredFilePath))
                return NotFound("Physical file missing");

            if (doc.IsEncrypted)
            {
                try {
                    var plainStream = await _encryptionService.DecryptFileAsync(doc.StoredFilePath);
                    // Return file
                    return File(plainStream, doc.ContentType, doc.OriginalFileName);
                }
                catch(Exception ex)
                {
                    return StatusCode(500, "Decryption failed: " + ex.Message);
                }
            }
            else
            {
                var stream = new FileStream(doc.StoredFilePath, FileMode.Open, FileAccess.Read);
                return File(stream, doc.ContentType, doc.OriginalFileName);
            }
        }
    }
}
